# Services
services:
  # Server service
  server:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb+srv://lebitl1x:VAt3PecOLtTBmN0x@dockersbd.drqhdog.mongodb.net/?retryWrites=true&w=majority&
      - appName=DockerSBD
      - PORT = 4000

  # Client service
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - server